import type { Project } from '../types'

export const INITIAL_PROJECTS: Project[] = [
    {
        id: '1',
        title: 'E-commerce Dashboard',
        description: 'A modern dashboard for online store management with analytics.',
        createdAt: '2 hours ago',
        updatedAt: '2 hours ago',
        rawUpdatedAt: new Date().toISOString(),
        isStarred: false,
        isSharedAsTemplate: false,
        versionCount: 1,
        currentVersionId: 'v1',
        createdByUsername: 'demo_user',
    },
    {
        id: '2',
        title: 'Portfolio Site 2024',
        description: 'Minimalist personal portfolio showcasing design work and case studies.',
        createdAt: 'Yesterday',
        updatedAt: 'Yesterday',
        rawUpdatedAt: new Date(Date.now() - 86400000).toISOString(),
        isStarred: true,
        isSharedAsTemplate: false,
        versionCount: 3,
        currentVersionId: 'v3',
        createdByUsername: 'demo_user',
    },
    {
        id: '3',
        title: 'SaaS Landing Page',
        description: 'High-converting landing page for a B2B software product.',
        createdAt: '3 days ago',
        updatedAt: '3 days ago',
        rawUpdatedAt: new Date(Date.now() - 259200000).toISOString(),
        isStarred: false,
        isSharedAsTemplate: true,
        versionCount: 2,
        currentVersionId: 'v2',
        createdByUsername: 'demo_user',
    },
    {
        id: '4',
        title: 'Personal Blog Design',
        description: 'Clean and readable blog layout with dark mode support.',
        createdAt: 'Last week',
        updatedAt: 'Last week',
        rawUpdatedAt: new Date(Date.now() - 604800000).toISOString(),
        isStarred: true,
        isSharedAsTemplate: false,
        versionCount: 1,
        currentVersionId: 'v1',
        createdByUsername: 'demo_user',
    },
]
