// generated by `bun init`

declare module '*.svg' {
    /**
     * a path to the svg file
     */
    const path: `${string}.svg`
    export = path
}

declare module '*.module.css' {
    /**
     * a record of class names to their corresponding css module classes
     */
    const classes: { readonly [key: string]: string }
    export = classes
}

declare module '*.png' {
    const path: string
    export default path
}
