version: '3.8'

services:
    nginx-deployment:
        image: nginx:alpine
        container_name: december-nginx-deployments
        ports:
            - '8085:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ../../deployments:/var/www/december/deployments:ro
        restart: always
