events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name ~^(?<project_id>[a-zA-Z0-9\-]+)\.december\.localhost$;

        root /var/www/december/deployments/$project_id;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Cache static assets for performance
        location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|svg|woff|woff2|ttf|otf)$ {
            expires 1d;
            access_log off;
            add_header Cache-Control "public";
        }
    }
}
