// this file was generated by prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from 'path'

import dotenv from 'dotenv'
import { defineConfig } from 'prisma/config'

dotenv.config({
    path: path.resolve(process.cwd(), '../../.env'),
})

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        url: process.env['DATABASE_URL'],
    },
})
