import { Box, Text } from 'ink'
import TextInput from 'ink-text-input'
import React from 'react'

import { THEME } from '../../theme'
import { Spinner } from '../spinner'

import { PROVIDER_MENU_ITEMS } from './byok-provider-menu'
import { MenuFooter } from './menu-footer'

export const PROVIDER_NAMES: Record<string, string> = {
    ...Object.fromEntries(PROVIDER_MENU_ITEMS.map((item) => [item.value, item.label])),
    abliteration: 'Abliteration AI',
    abliterationai: 'Abliteration AI',
    'abliteration-ai': 'Abliteration AI',
    agentrouter: 'AgentRouter',
    'agentrouter.org': 'AgentRouter',
    agnes: 'Agnes AI',
    agnesai: 'Agnes AI',
    'agnes-ai': 'Agnes AI',
    airouter: 'AI Router',
    'ai-router': 'AI Router',
    aiand: 'AI&',
    aki: 'AKI.IO',
    'aki-io': 'AKI.IO',
    akiio: 'AKI.IO',
    ambient: 'Ambient',
    anthropic: 'Anthropic',
    arcee: 'Arcee AI',
    arceeai: 'Arcee AI',
    'arcee-ai': 'Arcee AI',
    auriko: 'Auriko',
    aurikoai: 'Auriko',
    'auriko-ai': 'Auriko',
    baseten: 'Baseten',
    basetenco: 'Baseten',
    'baseten-co': 'Baseten',
    cerebras: 'Cerebras',
    claude: 'Anthropic',
    codex: 'OpenAI',
    cohere: 'Cohere',
    dashscope: 'Qwen (DashScope)',
    december: 'December Cloud',
    december_proxy: 'December Cloud',
    deepseek: 'DeepSeek',
    fireworks: 'Fireworks AI',
    google: 'Google',
    gemini: 'Google AI Studio',
    groq: 'Groq',
    huggingface: 'Hugging Face',
    hyperbolic: 'Hyperbolic',
    kimi: 'Kimi',
    lmstudio: 'LM Studio',
    llamacpp: 'llama.cpp',
    meta: 'Meta',
    metaai: 'Meta',
    'meta-ai': 'Meta',
    minimax: 'MiniMax',
    minimaxai: 'MiniMax',
    'minimax-ai': 'MiniMax',
    mistral: 'Mistral',
    mistralai: 'Mistral',
    'mistral-ai': 'Mistral',
    moonshot: 'Moonshot AI',
    moonshoot: 'Moonshot AI',
    moonshotai: 'Moonshot AI',
    'moonshot-ai': 'Moonshot AI',
    nvidia: 'NVIDIA NIM',
    ollama: 'Ollama',
    openai: 'OpenAI',
    openrouter: 'OpenRouter',
    perplexity: 'Perplexity AI',
    poolside: 'Poolside',
    qwen: 'Qwen (DashScope)',
    sakana: 'Sakana AI',
    'sakana-ai': 'Sakana AI',
    sakanaai: 'Sakana AI',
    sarvam: 'Sarvam AI',
    sarvamai: 'Sarvam AI',
    'sarvam-ai': 'Sarvam AI',
    stepfun: 'StepFun (Global)',
    stepfunai: 'StepFun (Global)',
    'stepfun-ai': 'StepFun (Global)',
    upstage: 'Upstage Solar',
    upstageai: 'Upstage Solar',
    solar: 'Upstage Solar',
    thinkingmachines: 'Thinking Machines (Tinker)',
    tinker: 'Thinking Machines (Tinker)',
    inkling: 'Thinking Machines (Tinker)',
    sambanova: 'SambaNova Cloud',
    siliconflow: 'SiliconFlow',
    together: 'Together AI',
    xAI: 'xAI',
    xai: 'xAI',
    xiaomi: 'Xiaomi',
    mimo: 'Xiaomi',
    zai: 'ZAI',
    zhipu: 'Zhipu AI',
    zhipuai: 'Zhipu AI',
}

export const PROVIDER_KEY_URLS: Record<string, string> = {
    '302ai': 'https://doc.302.ai',
    abacus: 'https://abacus.ai/help/api',
    abliteration: 'https://abliteration.ai/console',
    'abliteration-ai': 'https://abliteration.ai/console',
    abliterationai: 'https://abliteration.ai/console',
    above: 'https://above.dev/',
    agentrouter: 'https://agentrouter.org/console/token',
    'agentrouter.org': 'https://agentrouter.org/console/token',
    agnes: 'https://platform.agnes-ai.com/settings/apiKeys',
    'agnes-ai': 'https://platform.agnes-ai.com/settings/apiKeys',
    agnesai: 'https://platform.agnes-ai.com/settings/apiKeys',
    'ai-router': 'https://ai-router.dev/keys',
    ai21: 'https://studio.ai21.com/account/account',
    aiand: 'https://console.aiand.com/api-keys',
    aihubmix: 'https://docs.aihubmix.com',
    ainetcafe: 'https://ainetcafe.com/',
    airouter: 'https://ai-router.dev/keys',
    aixy: 'https://aixy-gateway.com/',
    aki: 'https://aki.io/admin/user-dashboard',
    'aki-io': 'https://aki.io/admin/user-dashboard',
    akiio: 'https://aki.io/admin/user-dashboard',
    ambient: 'https://app.ambient.xyz/keys',
    amd: 'https://developer.amd.com.cn/',
    anthropic: 'https://console.anthropic.com/settings/keys',
    anyapi: 'https://docs.anyapi.ai',
    arcee: 'https://platform.arcee.ai/api/api-keys',
    'arcee-ai': 'https://platform.arcee.ai/api/api-keys',
    arceeai: 'https://platform.arcee.ai/api/api-keys',
    auriko: 'https://www.auriko.ai/dashboard',
    'auriko-ai': 'https://www.auriko.ai/dashboard',
    aurikoai: 'https://www.auriko.ai/dashboard',
    bailing: 'https://tbox.cn/',
    baseten: 'https://app.baseten.co/settings/api_keys',
    'baseten-co': 'https://app.baseten.co/settings/api_keys',
    basetenco: 'https://app.baseten.co/settings/api_keys',
    berget: 'https://berget.ai/',
    blueclaw: 'https://blueclaw.network/',
    bothub: 'https://bothub.ru/',
    cerebras: 'https://cloud.cerebras.ai/platform',
    chutes: 'https://chutes.ai/',
    clarifai: 'https://clarifai.com/settings/security',
    claude: 'https://console.anthropic.com/settings/keys',
    claudinio: 'https://claudin.io/',
    'cline-pass': 'https://cline.bot/',
    'cloudferro-sherlock': 'https://cloudferro.com/',
    'cloudflare-ai-gateway': 'https://developers.cloudflare.com/ai-gateway/',
    codex: 'https://platform.openai.com/api-keys',
    cohere: 'https://dashboard.cohere.com/api-keys',
    coralbricks: 'https://coralbricks.ai/',
    cortecs: 'https://cortecs.ai/',
    crof: 'https://crof.ai/',
    crossmodel: 'https://www.crossmodel.ai/docs',
    crusoe: 'https://console.crusoecloud.com/',
    daoxe: 'https://daoxe.com/',
    dashscope: 'https://dashscope.console.aliyun.com/apiKey',
    'dashscope-cn': 'https://dashscope.console.aliyun.com/apiKey',
    'dashscope-intl': 'https://dashscope.console.aliyun.com/apiKey',
    december: 'December Cloud',
    december_proxy: 'December Cloud',
    deepinfra: 'https://deepinfra.com/dash/api_keys',
    deepseek: 'https://platform.deepseek.com/api_keys',
    digitalocean: 'https://cloud.digitalocean.com/account/api/tokens',
    dinference: 'https://dinference.com/',
    drun: 'https://d.run/',
    ebcloud: 'https://ebcloud.com/',
    echo: 'https://tracerml.ai/',
    edenai: 'https://docs.edenai.co',
    empiriolabs: 'https://empiriolabs.ai/',
    evroc: 'https://evroc.com/',
    fastrouter: 'https://fastrouter.ai/models',
    fireworks: 'https://app.fireworks.ai/api-keys',
    freemodel: 'https://freemodel.dev/',
    friendli: 'https://suite.friendli.ai/',
    frogbot: 'https://frogbot.ai/',
    gemini: 'https://aistudio.google.com/app/apikey',
    gmicloud: 'https://console.gmi-serving.com/',
    google: 'https://aistudio.google.com/app/apikey',
    greenpt: 'https://greenpt.ai/',
    groq: 'https://console.groq.com/keys',
    helicone: 'https://helicone.ai/models',
    hetzner: 'https://console.hetzner.cloud/',
    'hpc-ai': 'https://hpc-ai.com/',
    huggingface: 'https://huggingface.co/settings/tokens',
    hyper: 'https://hyper.charm.land/',
    hyperbolic: 'https://app.hyperbolic.ai/settings',
    iflowcn: 'https://iflow.cn/',
    impossibl: 'https://impossibl.com/',
    inception: 'https://inceptionlabs.ai/',
    inceptron: 'https://inceptron.io/',
    inco: 'https://inco.ai/',
    infer: 'https://flow7.org/',
    inference: 'https://inference.net/',
    inferx: 'https://inferx.net/',
    inkling: 'https://tinker.thinkingmachines.ai/',
    'io-net': 'https://cloud.io.net/',
    iteracompute: 'https://iteracompute.com/',
    jalapeno: 'https://jalapeno-cloud.ai/',
    jiekou: 'https://jiekou.ai/',
    kenari: 'https://kenari.id/',
    kilo: 'https://kilo.ai',
    kimi: 'https://platform.moonshot.ai/console/api-keys',
    'kimi-code-plan-cn': 'https://www.kimi.com/code/docs/en/kimi-code/models.html',
    'kimi-code-plan-global': 'https://www.kimi.ai/code/docs/en/kimi-code/models.html',
    klokintegration: 'https://klokintegration.se/',
    kosmik: 'https://koscompute.com/',
    lilac: 'https://getlilac.com/',
    llama: 'https://llama.com/',
    llamacpp: 'https://github.com/ggerganov/llama.cpp',
    llmgateway: 'https://llmgateway.io/docs',
    'llmgateway-providers': 'https://llmgateway.io/docs',
    llmtech: 'https://llmtech.eu/',
    llmtr: 'https://llmtr.com/',
    lmstudio: 'https://lmstudio.ai/',
    longcat: 'https://longcat.chat/',
    lucidquery: 'https://lucidquery.com/',
    meganova: 'https://meganova.ai/',
    melious: 'https://melious.ai/',
    'merge-gateway': 'https://docs.merge.dev/merge-gateway',
    meta: 'https://dev.meta.ai/',
    'meta-ai': 'https://dev.meta.ai/',
    metaai: 'https://dev.meta.ai/',
    mimo: 'https://platform.xiaomimimo.com/console/api-keys',
    minimax: 'https://platform.minimax.io/console/access',
    'minimax-ai': 'https://platform.minimax.io/console/access',
    minimaxai: 'https://platform.minimax.io/console/access',
    mistral: 'https://console.mistral.ai/api-keys/',
    'mistral-ai': 'https://console.mistral.ai/api-keys/',
    mistralai: 'https://console.mistral.ai/api-keys/',
    mixlayer: 'https://docs.mixlayer.com',
    moark: 'https://moark.com/docs/openapi/v1#tag/%E6%96%87%E6%9C%AC%E7%94%9F%E6%88%90',
    modal: 'https://modal.com/settings',
    'model-oracle-ai': 'https://modeloracle.com/setup/',
    modelis: 'https://modelishub.com/pricing',
    modelscope: 'https://modelscope.cn/my/myaccesstoken',
    moonshoot: 'https://platform.moonshot.ai/console/api-keys',
    moonshot: 'https://platform.moonshot.ai/console/api-keys',
    'moonshot-ai': 'https://platform.moonshot.ai/console/api-keys',
    moonshotai: 'https://platform.moonshot.ai/console/api-keys',
    morph: 'https://morphllm.com/',
    nan: 'https://nan.builders/',
    'nano-gpt': 'https://nano-gpt.com/api',
    nearai: 'https://cloud.near.ai/',
    nebius: 'https://tokenfactory.nebius.com/',
    neosmith: 'https://neosmith.ai/',
    neuralwatt: 'https://neuralwatt.com/',
    nova: 'https://aws.amazon.com/nova/',
    'novita-ai': 'https://novita.ai/settings/key-management',
    nvidia: 'https://build.nvidia.com/',
    ofox: 'https://ofox.ai/',
    ollama: 'https://ollama.com/download',
    'ollama-cloud': 'https://ollama.com/',
    openai: 'https://platform.openai.com/api-keys',
    opencode: 'https://opencode.ai/docs/zen',
    'opencode-go': 'https://opencode.ai/docs/go',
    openreason: 'https://openreason.app/',
    openrouter: 'https://openrouter.ai/settings/keys',
    opper: 'https://opper.ai/models',
    orcarouter: 'https://docs.orcarouter.ai',
    ovhcloud: 'https://endpoints.kepler.ai.cloud.ovh.net/',
    pendra: 'https://pendra.ai/',
    perplexity: 'https://www.perplexity.ai/settings/api',
    'perplexity-agent': 'https://docs.perplexity.ai/docs/agent-api/models',
    pioneer: 'https://pioneer.ai/',
    poe: 'https://poe.com/api_key',
    poolside: 'https://platform.poolside.ai/api-keys',
    'qihang-ai': 'https://qhaigc.net/',
    'qiniu-ai': 'https://portal.qiniu.com/',
    qvac: 'https://qvac.ai/',
    qwen: 'https://dashscope.console.aliyun.com/apiKey',
    'regolo-ai': 'https://docs.regolo.ai/',
    requesty: 'https://requesty.ai/solution/llm-routing/models',
    'routing-run': 'https://docs.routing.run/api-reference/models',
    runinfra: 'https://runinfra.ai/docs',
    sakana: 'https://console.sakana.ai/api-keys',
    'sakana-ai': 'https://console.sakana.ai/api-keys',
    sakanaai: 'https://console.sakana.ai/api-keys',
    'salad-cloud': 'https://portal.salad.com/',
    sambanova: 'https://cloud.sambanova.ai/apis',
    sarvam: 'https://dashboard.sarvam.ai/api-keys',
    'sarvam-ai': 'https://indus.sarvam.ai/',
    sarvamai: 'https://indus.sarvam.ai/',
    scaleway: 'https://console.scaleway.com/project/credentials',
    'scx-ai': 'https://scx.ai/',
    sensenova: 'https://platform.sensenova.cn/',
    siliconcloud: 'https://cloud.siliconflow.cn/account/ak',
    siliconflow: 'https://cloud.siliconflow.com/account/ak',
    'siliconflow-cn': 'https://cloud.siliconflow.cn/account/ak',
    solar: 'https://console.upstage.ai',
    stackit: 'https://portal.stackit.cloud/',
    standardcompute: 'https://standardcompute.com/models',
    stepfun: 'https://platform.stepfun.ai/interface-key',
    'stepfun-ai': 'https://platform.stepfun.ai/interface-key',
    stepfunai: 'https://platform.stepfun.ai/interface-key',
    subconscious: 'https://subconscious.dev/',
    submodel: 'https://submodel.ai/',
    synthetic: 'https://synthetic.new/',
    tempr: 'https://temprhq.io/',
    'tencent-tokenhub': 'https://cloud.tencent.com/product/hunyuan',
    tensorx: 'https://tensorx.ai/',
    'the-grid-ai': 'https://thegrid.ai/',
    thinkingmachines: 'https://tinker.thinkingmachines.ai/',
    tinfoil: 'https://tinfoil.sh/',
    tinker: 'https://tinker.thinkingmachines.ai/',
    together: 'https://api.together.ai/settings/api-keys',
    togetherai: 'https://api.together.ai/settings/api-keys',
    tokengo: 'https://www.tokengo.com/docs',
    tokenrouter: 'https://www.tokenrouter.com/docs/tokenrouter-feature-guide/',
    trustedrouter: 'https://trustedrouter.com/docs',
    'umans-ai': 'https://code.umans.ai/',
    unorouter: 'https://unorouter.com/models',
    upstage: 'https://console.upstage.ai/api-keys',
    upstageai: 'https://console.upstage.ai',
    v0: 'https://v0.dev/',
    vancine: 'https://vancine.com/',
    venice: 'https://venice.ai/settings/api',
    vercel: 'https://github.com/vercel/ai/tree/5eb85cc45a259553501f535b8ac79a77d0e79223/packages/gateway',
    vispark: 'https://vispark.in/',
    vivgrid: 'https://vivgrid.com/',
    volcengine: 'https://console.volcengine.com/ark',
    vultr: 'https://my.vultr.com/settings/#settingsapi',
    'wafer.ai': 'https://wafer.ai/',
    wallaby: 'https://wallabytoken.com/docs',
    wandb: 'https://wandb.ai/authorize',
    watsonx: 'https://cloud.ibm.com/iam/apikeys',
    xAI: 'https://console.x.ai/',
    xai: 'https://console.x.ai/',
    xiaomi: 'https://platform.xiaomimimo.com/console/api-keys',
    xpersona: 'https://www.xpersona.co/',
    zai: 'https://z.ai/manage-apikey/apikey-list',
    zeldoc: 'https://zeldoc.ai/',
    zenifra: 'https://zenifra.com/',
    zenmux: 'https://docs.zenmux.ai',
    zhipu: 'https://open.bigmodel.cn/usercenter/apikeys',
    zhipuai: 'https://open.bigmodel.cn/usercenter/apikeys',
}

export function formatProviderName(provider?: string): string {
    if (!provider) return 'Provider'
    return PROVIDER_NAMES[provider] || provider.charAt(0).toUpperCase() + provider.slice(1)
}

export function ByokKeyMenu(props: any) {
    const { selectedProvider, apiKey, setApiKey, handleKeySubmit, isStreaming, authError } = props
    const formattedProvider = formatProviderName(selectedProvider)
    const keyUrl = selectedProvider ? PROVIDER_KEY_URLS[selectedProvider] : undefined

    return (
        <Box flexDirection="column" paddingX={THEME.padding.paddingX}>
            <Box flexDirection="column" marginBottom={1}>
                <Text color={THEME.colors.text}>Enter API Key for {formattedProvider}:</Text>
                {keyUrl && (
                    <Text italic color={THEME.colors.muted}>
                        {"Don't have an API key? Get one at "}
                        <Text color={THEME.colors.brand}>{keyUrl}</Text>
                    </Text>
                )}
            </Box>
            <Box>
                <Text color={THEME.colors.brand} bold={false}>
                    {`${THEME.glyphs.prompt} `}
                </Text>
                <TextInput
                    focus={!isStreaming}
                    value={apiKey}
                    onChange={setApiKey}
                    onSubmit={handleKeySubmit}
                />
            </Box>
            {isStreaming ? (
                <Box marginTop={1}>
                    <Spinner label={`Verifying and saving API key for ${formattedProvider}...`} />
                </Box>
            ) : (
                <>
                    {authError && (
                        <Box marginTop={1}>
                            <Text color={THEME.colors.error}>{authError}</Text>
                        </Box>
                    )}
                    <MenuFooter
                        items={[
                            { key: 'enter', label: 'Submit' },
                            { key: 'esc', label: 'Cancel' },
                        ]}
                    />
                </>
            )}
        </Box>
    )
}
